### ISSUE TITLE
Support gRPC client

### ISSUE THREAD

**Issue by lcacciagioni** [commanded/commanded-extreme-adapter#29]
This might not make sense given this package name (The new gPRC client is named Spear), but is there any plan to support in the near future the new gRPC interface of EventstoreDB?
If that's the case, is there anything I can do to help?

**Comment by slashdotdash** [comment]
It would make sense to create a new library, such as `commanded_spear_adapter`, to use the Spear library and gRPC interface. 

I don't have any plans to do this since I don't use EventStoreDB but would be happy to help if someone else is keen to implement a Spear compatible adapter. Copying this GitHub repo as the basis for switching from Extreme to Spear would be a good way of starting.

**Comment by lcacciagioni** [comment]
Thanks @slashdotdash would give it a try during the week.
